### ISSUE TITLE
Newsletter sign-up

### ISSUE THREAD

**Issue by jperasmus** [how-to-firebase/full-stack-firebase#10]
Hi,

Not sure if you're getting any sign-ups to the newsletter because I see the whole form is currently just an image: https://www.fullstackfirebase.com/#newsletter 👻

Very interested in signing up for the newsletter.

**Comment by deltaepsilon** [comment]
Ugh. Yeah... that's a limitation of the GitBook platform. They won't let me link out from full-sized images like that.

I put a link below the image to hopefully solve that, but it's obviously not effective enough. I'll try to fix it today.

Thanks for giving me the heads up!

...and [here's the sign-up link](http://eepurl.com/ceGkov) :)

**Comment by jperasmus** [comment]
Thanks for the link.

To be honest, I did not see the link before. I would recommend removing the image altogether and just have the link. At the moment, it just seems like the implementation of the form was forgotten.

Keep doing the great work you're doing.

**Comment by deltaepsilon** [comment]
Sounds good. I'll take care of that. Thanks for the feedback!
