### ISSUE TITLE
Extra package.json, node_modules when following instructions in Firebase Tools > Walkthrough

### ISSUE THREAD

**Issue by dannymcgee** [how-to-firebase/full-stack-firebase#11]
Initializing Firebase automatically creates a "functions" directory inside the project directory with a `package.json`, `package-lock.json`, and `node_modules` directory. Later on, under **Deploy Pipeline**, the walkthrough says to run `npm init` and then install firebase-tools locally, which creates _another_ `package.json`, `package-lock.json`, and `node_modules` directory, this time in the project's root. Is this expected? It's pretty confusing and I'm not sure how to proceed.

**Comment by deltaepsilon** [comment]
Thanks for the suggestion!

Yes, this is intended. It's weird, but the `./functions/` folder is a separate Node project from the root directory.

I've added a note about this at the following commit: [6f96681](https://github.com/how-to-firebase/full-stack-firebase/commit/6f96681d45c1c4892423f9a16cbf0d75cbb9826a)
