### ISSUE TITLE
request.auth.token.admin got error

### ISSUE THREAD

**Issue by kuboon** [how-to-firebase/full-stack-firebase#12]
in this page https://github.com/how-to-firebase/full-stack-firebase/blob/master/cloud-firestore/security-rules.md

you say
```
request.auth.token.admin == true
```
But it does not look there is `admin` property in the `request.auth.token` object.

I'm finding the way to detect admin access in the rules and found your gitbook. Unfortunately it does not work currently.

**Comment by kuboon** [comment]
sorry it was my misunderstanding.

**Comment by deltaepsilon** [comment]
Security rules can be very tricky. They trip me up consistently.

**Comment by emmanuelviniciusdev** [comment]
What is the solution?

**Comment by deltaepsilon** [comment]
I don't think there was ever an issue with it. @kuboon just misunderstood something. Just use `request.auth.token.admin`.

**Comment by emmanuelviniciusdev** [comment]
That was my misunderstanding too! I was not passing the "admin" token to the simulator when I was making my firebase requests.

**Comment by deltaepsilon** [comment]
Phew! It's always nice to find answers in the GitHub issues.

I just implemented custom claims again a couple of hours ago and I can confirm that it works as designed :)
